package com.nikichxp.tgbot.core.dto

import com.fasterxml.jackson.annotation.JsonProperty
import com.nikichxp.tgbot.core.dto.dice.Dice
import com.nikichxp.tgbot.core.dto.files.Animation
import com.nikichxp.tgbot.core.dto.files.Audio
import com.nikichxp.tgbot.core.dto.files.Document
import com.nikichxp.tgbot.core.dto.files.PhotoSize
import com.nikichxp.tgbot.core.dto.files.Video
import com.nikichxp.tgbot.core.dto.files.VideoNote
import com.nikichxp.tgbot.core.dto.files.Voice
import com.nikichxp.tgbot.core.dto.payments.SuccessfulPayment
import com.nikichxp.tgbot.core.dto.polls.Poll
import com.nikichxp.tgbot.core.dto.stickers.Sticker

data class Message(
    @JsonProperty("message_id") val messageId: Long,
    @JsonProperty("message_thread_id") val messageThreadId: Long? = null,
    val from: User? = null,
    @JsonProperty("sender_chat") val senderChat: Chat? = null,
    @JsonProperty("sender_boost_count") val senderBoostCount: Int? = null,
    @JsonProperty("sender_business_bot") val senderBusinessBot: User? = null,
    val date: Long,
    @JsonProperty("business_connection_id") val businessConnectionId: String? = null,
    val chat: Chat,
    @JsonProperty("forward_origin") val forwardOrigin: MessageOrigin? = null,
    @JsonProperty("forward_from") val forwardFrom: User? = null,
    @JsonProperty("forward_from_chat") val forwardFromChat: Chat? = null,
    @JsonProperty("forward_from_message_id") val forwardFromMessageId: Int? = null,
    @JsonProperty("forward_signature") val forwardSignature: String? = null,
    @JsonProperty("forward_sender_name") val forwardSenderName: String? = null,
    @JsonProperty("forward_date") val forwardDate: Int? = null,
    @JsonProperty("is_topic_message") val isTopicMessage: Boolean? = null,
    @JsonProperty("is_automatic_forward") val isAutomaticForward: Boolean? = null,
    @JsonProperty("reply_to_message") val replyToMessage: Message? = null,
    @JsonProperty("external_reply") val externalReply: ExternalReplyInfo? = null,
    val quote: TextQuote? = null,
    @JsonProperty("reply_to_story") val replyToStory: Story? = null,
    @JsonProperty("via_bot") val viaBot: User? = null,
    @JsonProperty("edit_date") val editDate: Int? = null,
    @JsonProperty("has_protected_content") val hasProtectedContent: Boolean? = null,
    @JsonProperty("is_from_offline") val isFromOffline: Boolean? = null,
    @JsonProperty("media_group_id") val mediaGroupId: String? = null,
    @JsonProperty("author_signature") val authorSignature: String? = null,
    @JsonProperty("paid_star_count") val paidStarCount: Int? = null,
    val text: String? = null,
    @JsonProperty("link_preview_options") val linkPreviewOptions: LinkPreviewOptions? = null,
    @JsonProperty("effect_id") val effectId: String? = null,
    val entities: List<MessageEntity>? = null,
    @JsonProperty("caption_entities") val captionEntities: List<MessageEntity>? = null,
    val audio: Audio? = null,
    val document: Document? = null,
    val animation: Animation? = null,
    @JsonProperty("dice") val dice: Dice? = null,
    val game: Game? = null,
    val photo: List<PhotoSize>? = null,
    val sticker: Sticker? = null,
    val video: Video? = null,
    val voice: Voice? = null,
    @JsonProperty("video_note") val videoNote: VideoNote? = null,
    @JsonProperty("paid_media") val paidMedia: PaidMediaInfo? = null,
    val caption: String? = null,
    @JsonProperty("show_caption_above_media") val showCaptionAboveMedia: Boolean? = null,
    @JsonProperty("has_media_spoiler") val hasMediaSpoiler: Boolean? = null,
    val contact: Contact? = null,
    val location: Location? = null,
    val venue: Venue? = null,
    @JsonProperty("new_chat_members") val newChatMembers: List<User>? = null,
    val poll: Poll? = null,
    @JsonProperty("left_chat_member") val leftChatMember: User? = null,
    @JsonProperty("new_chat_title") val newChatTitle: String? = null,
    @JsonProperty("new_chat_photo") val newChatPhoto: List<PhotoSize>? = null,
    @JsonProperty("delete_chat_photo") val deleteChatPhoto: Boolean? = null,
    @JsonProperty("group_chat_created") val groupChatCreated: Boolean? = null,
    @JsonProperty("supergroup_chat_created") val supergroupChatCreated: Boolean? = null,
    @JsonProperty("channel_chat_created") val channelChatCreated: Boolean? = null,
    @JsonProperty("message_auto_delete_timer_changed") val messageAutoDeleteTimerChanged: MessageAutoDeleteTimerChanged? = null,
    @JsonProperty("migrate_to_chat_id") val migrateToChatId: Long? = null,
    @JsonProperty("migrate_from_chat_id") val migrateFromChatId: Long? = null,
    @JsonProperty("pinned_message") val pinnedMessage: Message? = null,
    val invoice: Invoice? = null,
    @JsonProperty("successful_payment") val successfulPayment: SuccessfulPayment? = null,
    @JsonProperty("refunded_payment") val refundedPayment: RefundedPayment? = null,
    @JsonProperty("users_shared") val usersShared: UsersShared? = null,
    @JsonProperty("chat_shared") val chatShared: ChatShared? = null,
    @JsonProperty("connected_website") val connectedWebsite: String? = null,
    @JsonProperty("write_access_allowed") val writeAccessAllowed: WriteAccessAllowed? = null,
    @JsonProperty("passport_data") val passportData: PassportData? = null,
    @JsonProperty("proximity_alert_triggered") val proximityAlertTriggered: ProximityAlertTriggered? = null,
    @JsonProperty("boost_added") val boostAdded: ChatBoostAdded? = null,
    @JsonProperty("forum_topic_created") val forumTopicCreated: ForumTopicCreated? = null,
    @JsonProperty("forum_topic_edited") val forumTopicEdited: ForumTopicEdited? = null,
    @JsonProperty("forum_topic_closed") val forumTopicClosed: ForumTopicClosed? = null,
    @JsonProperty("forum_topic_reopened") val forumTopicReopened: ForumTopicReopened? = null,
    @JsonProperty("general_forum_topic_hidden") val generalForumTopicHidden: GeneralForumTopicHidden? = null,
    @JsonProperty("general_forum_topic_unhidden") val generalForumTopicUnhidden: GeneralForumTopicUnhidden? = null,
    @JsonProperty("giveaway_created") val giveawayCreated: GiveawayCreated? = null,
    val giveaway: Giveaway? = null,
    @JsonProperty("giveaway_winners") val giveawayWinners: GiveawayWinners? = null,
    @JsonProperty("giveaway_completed") val giveawayCompleted: GiveawayCompleted? = null,
    @JsonProperty("video_chat_scheduled") val videoChatScheduled: VideoChatScheduled? = null,
    @JsonProperty("video_chat_started") val videoChatStarted: VideoChatStarted? = null,
    @JsonProperty("video_chat_ended") val videoChatEnded: VideoChatEnded? = null,
    @JsonProperty("video_chat_participants_invited") val videoChatParticipantsInvited: VideoChatParticipantsInvited? = null,
    @JsonProperty("web_app_data") val webAppData: WebAppData? = null,
    @JsonProperty("reply_markup") val replyMarkup: InlineKeyboardMarkup? = null
)
