name: Deploy to server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deployment
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          command: |
            cd /app
            touch demofile-1.txt
            echo "Hello, World!" > demofile-1.txt
#            git pull
#            ./gradlew build
#            cd /app
#            docker-compose build
#            docker-compose up -d
